### ISSUE TITLE
site.yml not pushing the baceline PKG's to the nwly build servers

### ISSUE THREAD

**Issue by JP1GIT** [thbe/ansible-role-rhel#1]
site.yml not pushing the baceline PKG's to the newly build servers

below is the only error we are getting which pushing the site.yml but no baseline packages getting installed 

failed: [xx.xx.xx.xx] (item=dnf-plugin-diff) => changed=false
ansible_loop_var: item
failures :
 -No package dnf-plugin-diff available.
item: dnf-plugin-diff
msg: Failed to install some of the specified packages
rc :1
results : [ ]

**Comment by thbe** [comment]
On what type of server did you try to deploy the baseline role? dnf-plugin-diff is not part of this role, I wonder if this is maybe OS related. I'd tested the role on RockyLinux 8/ 9 and RHEL 8/ 9 but haven't seen the error there ...

**Comment by JP1GIT** [comment]
this is on the RHEL 8.6 Os and its taken place while running the 
TASK [rhel:Installation of RHEL packages]

**Comment by pulse452** [comment]
@thbe, no other specific errors showing while executing the site.yml. Everytime it is skipping most of the roles and configurations, but the result in the servers are not as we are expecting. Could you please help?

**Comment by thbe** [comment]
dnf-plugin-diff is no longer part of the RHEL role ...
